export const FETCH_TODO = "FETCH_TODO"
export const ADD_TODO = "ADD_TODO"
export const TOGGLE_TODO = "TOGGLE_TODO"
export const SET_VISIBILITY_FILTER = " SET_VISIBILITY_FILTER"

export const USER_NOT_EXIST = "USER_NOT_EXIST"
export const LOGGIN_FAIL = "LOGGIN_FAIL"
export const LOGGIN_SUCCESS = "LOGGIN_SUCCESS"


